# Runs operations/site-runner ansible playbook

name: Configure Server
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
env:
  PATH: /usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbin:./bin:./vendor/bin

jobs:
  playbook:
    strategy:
      fail-fast: false

    # runs-on: control@dashboard.operations.local.computer
    runs-on: ubuntu-latest
    container:  geerlingguy/docker-rockylinux8-ansible:latest

    steps:

      - name: Info
        run: |
          pwd
          hostname 
          whoami
          echo $PATH

      - name: Checkout codebase
        uses: actions/checkout@v4

      - name: Build codebase
        uses: php-actions/composer@v6
        with:
          command: install --ignore-platform-reqs

      - name: Configure System
        run: |
          ansible-playbook vendor/operations/site-runner/playbook.yml  --limit $(hostname -f),sites --connection local